title: overcodeddotmisaki
author:
    name: hieutt99
    email: hieutt99@gmail.com
    avatar: 
    bio: "temp"

# description: >- # this means to ignore newlines until "baseurl:"
description: >+ # this means to ignore newlines until "show_excerpts:"
    “There are no facts, only interpretations.”      
    ~ Friedrich Nietzsche ~

search: true


# Build settings
markdown: kramdown
theme: minima


# # Outputting
permalink: /:year/:month/:day/:title/
timezone: Asia/Ho_Chi_Minh


# show_excerpts: false # set to true to show excerpts on the homepage
show_excerpts: true

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
    skin: dark
    date_format: "%b %-d, %Y"

    # generate social links in footer
    social_links:
        # twitter: jekyllrb
        github:  hieutt99
        # devto: jekyll
        # dribbble: jekyll
        # facebook: jekyll
        # flickr:   jekyll
        # instagram: jekyll
        linkedin: hieutt99
        # pinterest: jekyll
        # youtube: jekyll
        # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
        # youtube_channel_name: CloudCannon
        # telegram: jekyll
        # googleplus: +jekyll
        # microdotblog: jekyll
        # keybase: jekyll

        # Mastodon instances
        # mastodon:
        # - username: jekyll
        #   instance: example.com
        # - username: jekyll2
        #   instance: example.com

        # GitLab instances
        # gitlab:
        # - username: jekyll
        #   instance: example.com
        # - username: jekyll2
        #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
- about.md

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache